image: golang

stages:
    - build
    - test

build:
    stage: build
    script:
        - echo "Building"
        - mkdir build
        - touch build/info.txt
        - cp -r . /go/src/ibs
    artifacts:
        paths:
            - build/

test:
    stage: test
    script:
        - echo "Testing dev branch 24/11/19"
        - test -f "build/info.txt"
        - go test ./... -
